#!/usr/bin/env python
# To be used from mutt. Reads message from stdin, extracts message-id,
# asks for args for notmuch tag.
# Executes: notmuch tag [your args] id:[message-id]
# This line in muttrc:
# macro pager "\CB" "<pipe-message>~/.mutt/mutt-tag " "Tag message with notmuch"
#
# after pressing ^b you'll have to write +tag,-tag part and push enter.


import sys
from subprocess import call
from email.Parser import Parser


def main():
    msg = sys.stdin.read()
    p = Parser()
    msgJustHeaders = p.parsestr(msg, True)
    mid = None
    if 'Message-ID' in msgJustHeaders:
        mid = msgJustHeaders['Message-ID']
    elif 'Message-Id' in msgJustHeaders:
        mid = msgJustHeaders['Message-Id']
    if mid:
        mid = mid.lstrip('<')
        mid = mid.rstrip('>')
        var = ' '.join(sys.argv[1:])
        cmd = "notmuch tag %s id:%s" % (var, mid)
        print "Will call ", cmd
        ret = call(cmd.split())
        sys.exit(ret)
    else:
        print("No message-id header found")

if __name__ == "__main__":
    main()
# vim: set ts=4 sw=4 tw=72 ft=python:
